import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { metaApiClient } from "../meta/client.js";
import { buildFieldsParam } from "../utils/validation.js";
import { truncateResponse } from "../utils/format.js";
import { LEAD_FORM_DEFAULT_FIELDS, LEAD_DEFAULT_FIELDS } from "../meta/types/lead.js";
import type { LeadForm, Lead, MetaApiResponse } from "../meta/types/index.js";

export function registerLeadTools(server: McpServer): void {
  // ─── Get Lead Forms ───────────────────────────────────────────
  server.tool(
    "meta_ads_get_lead_forms",
    "List lead generation forms for a Facebook Page. Returns form details including questions, status, and lead count.",
    {
      page_id: z.string().describe("Facebook Page ID"),
      limit: z.number().min(1).max(100).default(25),
      fields: z.array(z.string()).optional().describe("Fields to retrieve"),
    },
    async ({ page_id, limit, fields }) => {
      const fieldsParam = buildFieldsParam(fields, [...LEAD_FORM_DEFAULT_FIELDS]);

      const response = await metaApiClient.get<MetaApiResponse<LeadForm>>(
        `/${page_id}/leadgen_forms`,
        { fields: fieldsParam, limit },
      );
      const forms = response.data ?? [];

      const text =
        forms.length === 0
          ? "No lead forms found."
          : forms
              .map(
                (f) =>
                  `• ${f.name} (${f.id}) — Status: ${f.status} — Leads: ${f.leads_count ?? "N/A"}`,
              )
              .join("\n");

      return {
        content: [
          { type: "text", text: `Found ${forms.length} lead form(s):\n\n${text}` },
          { type: "text", text: JSON.stringify(forms, null, 2) },
        ],
      };
    },
  );

  // ─── Get Leads from Form ──────────────────────────────────────
  server.tool(
    "meta_ads_get_leads",
    "Download leads from a lead generation form. Returns lead data including field values, timestamps, and associated ad/campaign info.",
    {
      form_id: z.string().describe("Lead form ID"),
      limit: z.number().min(1).max(500).default(100),
      fields: z.array(z.string()).optional().describe("Fields to retrieve"),
      filtering: z
        .array(
          z.object({
            field: z.string(),
            operator: z.string(),
            value: z.union([z.string(), z.number()]),
          }),
        )
        .optional()
        .describe("Filter leads (e.g., by time_created)"),
    },
    async ({ form_id, limit, fields, filtering }) => {
      const fieldsParam = buildFieldsParam(fields, [...LEAD_DEFAULT_FIELDS]);

      const params: Record<string, string | number | boolean> = {
        fields: fieldsParam,
        limit,
      };

      if (filtering && filtering.length > 0) {
        params.filtering = JSON.stringify(filtering);
      }

      const response = await metaApiClient.get<MetaApiResponse<Lead>>(
        `/${form_id}/leads`,
        params,
      );
      const leads = response.data ?? [];

      if (leads.length === 0) {
        return {
          content: [{ type: "text", text: "No leads found for this form." }],
        };
      }

      const summary = leads
        .slice(0, 10)
        .map((l) => {
          const fieldSummary = l.field_data
            .map((f) => `${f.name}: ${f.values.join(", ")}`)
            .join(" | ");
          return `• ${l.id} (${l.created_time}) — ${fieldSummary}`;
        })
        .join("\n");

      const jsonStr = truncateResponse(JSON.stringify(leads, null, 2));

      return {
        content: [
          {
            type: "text",
            text: `Found ${leads.length} lead(s)${leads.length > 10 ? ` (showing first 10 in summary)` : ""}:\n\n${summary}`,
          },
          { type: "text", text: jsonStr },
        ],
      };
    },
  );

  // ─── Get Leads from Ad ────────────────────────────────────────
  server.tool(
    "meta_ads_get_ad_leads",
    "Get leads generated by a specific ad. Useful for analyzing lead quality per ad variant.",
    {
      ad_id: z.string().describe("Ad ID"),
      limit: z.number().min(1).max(500).default(100),
      fields: z.array(z.string()).optional(),
    },
    async ({ ad_id, limit, fields }) => {
      const fieldsParam = buildFieldsParam(fields, [...LEAD_DEFAULT_FIELDS]);

      const response = await metaApiClient.get<MetaApiResponse<Lead>>(
        `/${ad_id}/leads`,
        { fields: fieldsParam, limit },
      );
      const leads = response.data ?? [];

      if (leads.length === 0) {
        return {
          content: [{ type: "text", text: `No leads found for ad ${ad_id}.` }],
        };
      }

      const jsonStr = truncateResponse(JSON.stringify(leads, null, 2));

      return {
        content: [
          { type: "text", text: `Found ${leads.length} lead(s) for ad ${ad_id}.` },
          { type: "text", text: jsonStr },
        ],
      };
    },
  );

  // ─── Create Lead Form ─────────────────────────────────────────
  server.tool(
    "meta_ads_create_lead_form",
    "Create a new lead generation form for a Facebook Page.",
    {
      page_id: z.string().describe("Facebook Page ID"),
      name: z.string().min(1).describe("Form name"),
      questions: z
        .array(
          z.object({
            type: z.string().describe("Question type (e.g., FULL_NAME, EMAIL, PHONE_NUMBER, CUSTOM)"),
            key: z.string().optional().describe("Custom question key"),
            label: z.string().optional().describe("Custom question label"),
          }),
        )
        .describe("Form questions"),
      privacy_policy_url: z.string().describe("Privacy policy URL (required by Meta)"),
      follow_up_action_url: z.string().optional().describe("Thank you page URL"),
      locale: z.string().optional().describe("Form locale (e.g., en_US)"),
    },
    async ({ page_id, name, questions, privacy_policy_url, follow_up_action_url, locale }) => {
      const body: Record<string, string | number | boolean> = {
        name,
        questions: JSON.stringify(questions),
        privacy_policy: JSON.stringify({ url: privacy_policy_url }),
      };

      if (follow_up_action_url) body.follow_up_action_url = follow_up_action_url;
      if (locale) body.locale = locale;

      const result = await metaApiClient.postForm<{ id: string }>(
        `/${page_id}/leadgen_forms`,
        body,
      );

      return {
        content: [
          {
            type: "text",
            text: `Lead form created successfully!\nID: ${result.id}\nName: ${name}\nQuestions: ${questions.length}\nPage: ${page_id}`,
          },
        ],
      };
    },
  );
}
